//! Runs the full `setup -> prep_prove -> prove -> verify ->
//! verify_and_check_binding` pipeline against real-shaped, salted,
//! realistic mdoc claims from `test-vectors/*.json` (generated by
//! `examples/gen_test_mdocs.rs`) — the load-bearing end-to-end proof
//! that closing the real-interop gap (real, witnessed-length SHA-256 via
//! `sha256_var`, `MAX_CLAIM_BYTES_V1` raised to 128) actually works
//! against claim shapes this crate could never even accept before (real
//! `IssuerSignedItem` bytes with a real ≥16-byte salt run 79-103 bytes,
//! comfortably over the old 64-byte limit).
//!
//! This is a real, deliberately different kind of test from this crate's
//! existing unit tests, which all use short, unsalted, hand-picked byte
//! strings the same test also signs. These fixtures were minted by an
//! independent generator (real CBOR encoding, real salts, real ECDSA
//! signing over the real MSO `Sig_structure`, decoded and spot-checked
//! with an independent Python `cbor2` pass before being committed — see
//! the generator's own module doc) — this test consumes them exactly the
//! way the crate's own claim-fixed-width padding did NOT allow until now.

use serde::Deserialize;
use zk_cred_vega::mso::MsoBodyWitness;
use zk_cred_vega::{ClaimWitness, MdocEcdsaWitness};

#[derive(Deserialize)]
struct FixtureClaim {
  #[allow(dead_code)]
  element_identifier: String,
  digest_id: u64,
  disclose: bool,
  issuer_signed_item_bytes_hex: String,
  issuer_signed_item_bytes_len: usize,
}

#[derive(Deserialize)]
struct FixtureEcdsaWitness {
  qx_hex: String,
  qy_hex: String,
  r_hex: String,
  s_hex: String,
  s_inv_hex: String,
}

#[derive(Deserialize)]
struct FixtureMsoBody {
  device_x_hex: String,
  device_y_hex: String,
  signed_ts: String,
  valid_from_ts: String,
  valid_until_ts: String,
}

#[derive(Deserialize)]
struct Fixture {
  #[allow(dead_code)]
  description: String,
  claims: Vec<FixtureClaim>,
  ecdsa_witness: FixtureEcdsaWitness,
  mso_body: FixtureMsoBody,
}

fn hex_bytes(s: &str) -> Vec<u8> {
  hex::decode(s).expect("valid hex")
}

fn fixed_bytes<const N: usize>(s: &str) -> [u8; N] {
  hex_bytes(s).try_into().expect("expected length")
}

#[test]
fn real_mdoc_fixture_round_trips_through_the_full_pipeline() {
  let raw = std::fs::read_to_string("test-vectors/mdl_4claims_mixed_disclosure.json")
    .expect("read fixture (run `cargo run --release --example gen_test_mdocs` if missing)");
  let fixture: Fixture = serde_json::from_str(&raw).expect("parse fixture");

  // The whole point: these are real IssuerSignedItem sizes (with a real
  // salt), well over the crate's old 64-byte limit and impossible to
  // even construct a ClaimWitness from before this session's fix.
  for c in &fixture.claims {
    assert!(
      c.issuer_signed_item_bytes_len > 64,
      "{}: fixture claim is only {} bytes -- this test is supposed to exercise \
       real (>64-byte) claim sizes; regenerate with a realistic element",
      c.element_identifier,
      c.issuer_signed_item_bytes_len
    );
    assert!(c.issuer_signed_item_bytes_len <= zk_cred_vega::MAX_CLAIM_BYTES_V1);
  }

  let claims: Vec<ClaimWitness> = fixture
    .claims
    .iter()
    .map(|c| {
      let bytes = hex_bytes(&c.issuer_signed_item_bytes_hex);
      assert_eq!(bytes.len(), c.issuer_signed_item_bytes_len);
      ClaimWitness {
        issuer_signed_item_bytes: bytes,
        disclose: c.disclose,
        digest_id: u32::try_from(c.digest_id).expect("fixture digestID fits in a u32 (spec bounds it at < 2^31)"),
      }
    })
    .collect();

  let ecdsa_witness = {
    use num_bigint::{BigInt, Sign};
    use zk_cred_vega::nonnative::util::nat_to_f;
    let qx = nat_to_f(&BigInt::from_bytes_be(Sign::Plus, &hex_bytes(&fixture.ecdsa_witness.qx_hex))).expect("qx fits");
    let qy = nat_to_f(&BigInt::from_bytes_be(Sign::Plus, &hex_bytes(&fixture.ecdsa_witness.qy_hex))).expect("qy fits");
    MdocEcdsaWitness {
      qx,
      qy,
      r: BigInt::from_bytes_be(Sign::Plus, &hex_bytes(&fixture.ecdsa_witness.r_hex)),
      s: BigInt::from_bytes_be(Sign::Plus, &hex_bytes(&fixture.ecdsa_witness.s_hex)),
      s_inv: BigInt::from_bytes_be(Sign::Plus, &hex_bytes(&fixture.ecdsa_witness.s_inv_hex)),
    }
  };

  let mso_body = MsoBodyWitness {
    device_x: fixed_bytes(&fixture.mso_body.device_x_hex),
    device_y: fixed_bytes(&fixture.mso_body.device_y_hex),
    signed_ts: fixture.mso_body.signed_ts.as_bytes().try_into().expect("20 bytes"),
    valid_from_ts: fixture.mso_body.valid_from_ts.as_bytes().try_into().expect("20 bytes"),
    valid_until_ts: fixture.mso_body.valid_until_ts.as_bytes().try_into().expect("20 bytes"),
  };

  let keys = zk_cred_vega::setup().expect("setup");
  let nonce = zk_cred_vega::fresh_nonce().expect("fresh_nonce");
  let prep = zk_cred_vega::prep_prove(&keys.pk, &claims, &ecdsa_witness, &mso_body, &nonce).expect("prep_prove");
  let (proof, _next_prep) =
    zk_cred_vega::prove(&keys.pk, &claims, &ecdsa_witness, &mso_body, prep, &nonce).expect("prove");
  let (step_public_values, core_public_values) = zk_cred_vega::verify(&proof, &keys.vk).expect("verify");

  let verified = zk_cred_vega::verify_and_check_binding(&step_public_values, &core_public_values)
    .expect("binding check must pass for a genuine real-shaped presentation");

  assert_eq!(verified.qx, ecdsa_witness.qx);
  assert_eq!(verified.qy, ecdsa_witness.qy);
  assert_eq!(verified.claims.len(), fixture.claims.len());

  for (verified_claim, expected) in verified.claims.iter().zip(fixture.claims.iter()) {
    assert_eq!(verified_claim.disclosed, expected.disclose);
    assert_eq!(verified_claim.real_len, expected.issuer_signed_item_bytes_len);
    assert_eq!(
      verified_claim.digest_id as u64, expected.digest_id,
      "{}: the real reference vector's own digestID must round-trip through the proof",
      expected.element_identifier
    );
    if expected.disclose {
      assert_eq!(
        verified_claim.plaintext,
        hex_bytes(&expected.issuer_signed_item_bytes_hex),
        "{}: disclosed plaintext must be the real IssuerSignedItem bytes, byte-for-byte",
        expected.element_identifier
      );
    } else {
      assert_eq!(
        verified_claim.plaintext,
        vec![0u8; expected.issuer_signed_item_bytes_len],
        "{}: undisclosed plaintext must be masked to all-zero",
        expected.element_identifier
      );
    }
  }
}
